[Themes] Optimize assets path resolution
lolautruche/EzCoreExtraBundle pull request #25
Opened 2017-05-03 15:26 UTC by lolautruche

Currently assets path resolution is done at runtime, which can cause a lot of I/O calls at every requests.

This PR adds a new asset path resolver, `ProvisionedPathResolver` and its companion `AssetPathResolutionPass` compiler pass.
Goal is to browse all theme folders and pre-resolve paths for found assets.

A setting has been added in order to enable/disable this feature.
Default behavior is to enable it only when debug is off (i.e. "production" environment).

2017-05-03 15:27 UTC, lolautruche commented
Still WIP, but main code is there.
Ping @emodric @bdunogier

2017-05-05 09:52 UTC, bdunogier requested changes
Good so far, waiting for the refactored & tested compiler pass :)

2017-05-05 09:52 UTC, bdunogier commented on Asset/ProvisionedPathResolver.php
> +     * {@inheritdoc}
It goes beyond this PR, but I'm still very skeptical at `@inheritdoc`. From where I stand, the documentation of the parent method is always inherited. The tag would be use to include the parent's doc into the child, as in _inline include_.

I personally just skip it, meaning that the documentation is identical to the parent's.

2017-05-05 09:58 UTC, bdunogier approved these changes
Looks good to me :)

2017-05-05 09:58 UTC, bdunogier commented on Asset/ProvisionedPathResolver.php
> +            foreach ((new Finder())->files()->in($themePath)->exclude('themes')->followLinks()->ignoreUnreadableDirs() as $fileInfo) {
You could maybe move this to a private method with a proper name, and move the inline comments as phpdoc of that method ?

2017-05-05 09:58 UTC, bdunogier commented on Tests/Asset/ProvisionedPathResolverTest.php
> +        $webrootDir = vfsStream::setup('web');
Did you consider moving this to `setUp()` ?

2017-05-05 10:39 UTC, emodric commented
@lolautruche Don't know if I can be of much help since I haven't used this part of the bundle yet, but if you're asking if this is breaking anything for Tags Bundle, I'd say no, since Tags Bundle only uses the security voter.

2017-05-05 12:09 UTC, lolautruche commented on Asset/ProvisionedPathResolver.php
> +     * {@inheritdoc}
Here this is perfectly valid since I override the description, adding something, then I call the parent 😁

2017-05-05 13:19 UTC, lolautruche commented on Asset/ProvisionedPathResolver.php
> +            foreach ((new Finder())->files()->in($themePath)->exclude('themes')->followLinks()->ignoreUnreadableDirs() as $fileInfo) {
Good point, thanks

2017-05-05 13:31 UTC, lolautruche commented
Thanks for the review guys!

2017-05-05 14:19 UTC, merged